#!/usr/bin/env bun
/**
 * build-lexicon.ts — mine a frequency lexicon/concordance from the corpus. This
 * is the project's positive-grounding artifact: every word the existing,
 * community-reviewed Scripture actually uses, how often, and where.
 *
 * Outputs (paths from the profile):
 *   <paths.lexicon>            — { meta, words: { word: {c: count, ex: [refs...] } } }
 *   <paths.lexicon>-summary.md — human-readable stats + top words
 *
 * The JSON powers check-draft.ts --lexicon (corpus-membership / hallucination
 * check): any word in a draft that never appears in the corpus is a probable
 * invention or a source-specific term to confirm.
 *
 * Usage: bun tools/build-lexicon.ts [--profile profiles/<iso>.json]
 */
import { writeFileSync } from "fs";
import { tokenize } from "./lib/tokenize.ts";
import { loadProfile, loadVerses } from "./lib/profile.ts";

const profile = loadProfile();
const OUT_JSON = profile.paths.lexicon;
const OUT_MD = OUT_JSON.replace(/\.json$/, "-summary.md");

const verses = loadVerses(profile.paths.corpus);

const lex: Record<string, { c: number; ex: string[] }> = {};
let totalTokens = 0;
let verseCount = 0;

for (const [ref, text] of Object.entries(verses)) {
  verseCount++;
  for (const tok of tokenize(text)) {
    totalTokens++;
    if (!lex[tok]) lex[tok] = { c: 0, ex: [] };
    lex[tok].c++;
    if (lex[tok].ex.length < 3 && !lex[tok].ex.includes(ref)) lex[tok].ex.push(ref);
  }
}

const sorted = Object.entries(lex).sort((a, b) => b[1].c - a[1].c);
const unique = sorted.length;

const outObj: Record<string, { c: number; ex: string[] }> = {};
for (const [w, v] of sorted) outObj[w] = v;
writeFileSync(
  OUT_JSON,
  JSON.stringify(
    { meta: { source: profile.language, verses: verseCount, total_tokens: totalTokens, unique_words: unique }, words: outObj },
    null,
    0,
  ),
);

const top = sorted.slice(0, 100);
const hapax = sorted.filter(([, v]) => v.c === 1).length;
let md = `# ${profile.language} — Frequency Lexicon (auto-generated)\n\n`;
md += `> Generated by \`tools/build-lexicon.ts\` from the corpus at \`${profile.paths.corpus}\`. Do not hand-edit; re-run the script.\n\n`;
md += `- **Verses:** ${verseCount}\n- **Total tokens:** ${totalTokens.toLocaleString()}\n- **Unique words:** ${unique.toLocaleString()}\n- **Hapax (appear once):** ${hapax.toLocaleString()} — these are the riskiest to reuse out of context\n\n`;
md += `The full word→{count, examples} map is in the lexicon JSON, consumed by \`check-draft.ts --lexicon\` as the corpus-membership oracle.\n\n`;
md += `## Top 100 words\n\n| # | word | count | example |\n|---|------|-------|---------|\n`;
top.forEach(([w, v], i) => {
  md += `| ${i + 1} | \`${w}\` | ${v.c} | ${v.ex[0] ?? ""} |\n`;
});
writeFileSync(OUT_MD, md);

console.log(`✓ ${verseCount} verses → ${unique} unique words (${totalTokens} tokens, ${hapax} hapax)`);
console.log(`  wrote ${OUT_JSON}`);
console.log(`  wrote ${OUT_MD}`);
