#!/usr/bin/env bun
/**
 * build-incontext-pack.ts — distill the corpus into a model-optimized in-context
 * pack: a core frequency vocabulary + pattern banks of REAL example verses.
 * Built on the finding that example sentences anchor a model to a low-resource
 * language better than human-style grammar prose. Every line is attested in the
 * corpus — nothing invented.
 *
 * Language-specific bits come from the profile:
 *   - paths.corpus, paths.lexicon, paths.incontext_pack    (where to read/write)
 *   - core_word_pattern                                     (which tokens count as core)
 *   - incontext_patterns[]  { name, note, pattern, flags, n } (construction banks)
 * If incontext_patterns is absent the pack is core-vocabulary only.
 *
 * Usage:  bun tools/build-incontext-pack.ts [--profile profiles/<iso>.json]
 */
import { readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { loadProfile, loadVerses, ROOT } from "./lib/profile.ts";

const profile = loadProfile();
const corpus = loadVerses(profile.paths.corpus);
const lex = JSON.parse(readFileSync(profile.paths.lexicon, "utf8")).words as Record<string, { c: number }>;
const entries = Object.entries(corpus);
const toks = (s: string) => s.split(/\s+/).length;

const outPath =
  profile.paths.incontext_pack ??
  join(ROOT, "references", `${profile.iso639_3}-incontext-pack.md`);

// Core vocabulary: top frequency forms that are "words" (letters/apostrophes only).
const coreRe = new RegExp(profile.core_word_pattern ?? "^[\\p{L}'ʼ]+$", "u");
const CORE = Object.entries(lex)
  .sort((a, b) => b[1].c - a[1].c)
  .map(([w]) => w)
  .filter((w) => coreRe.test(w))
  .slice(0, 120);

interface Pat { name: string; note: string; pattern: string; flags?: string; n?: number }
const PATTERNS: Pat[] = Array.isArray(profile.raw.incontext_patterns) ? profile.raw.incontext_patterns : [];

function pick(re: RegExp, n: number): [string, string][] {
  return entries.filter(([, t]) => re.test(t)).sort((a, b) => toks(a[1]) - toks(b[1])).slice(0, n);
}

let md = `# ${profile.language} — In-Context Pack (model-optimized, auto-generated)\n\n`;
md += `> Load this when drafting. It anchors you in REAL attested ${profile.language}. **Learn from the examples, not from rules** — every verse below is from the actual corpus. Prefer the vocabulary and constructions shown here; if a word you want isn't attested in the corpus, it is probably a borrowing from a wider-communication language — find the local form or mark it ⟨?⟩.\n\n`;
md += `Generated by \`tools/build-incontext-pack.ts\` from ${entries.length} corpus verses.\n\n`;

md += `## Core vocabulary (most frequent attested forms)\n\nReach for these. They are the backbone of real ${profile.language}:\n\n`;
md += "`" + CORE.join("` · `") + "`\n\n";

if (PATTERNS.length) {
  md += `## Pattern banks (anchor your grammar to these real verses)\n\n`;
  for (const p of PATTERNS) {
    const ex = pick(new RegExp(p.pattern, p.flags ?? "i"), p.n ?? 5);
    if (!ex.length) continue;
    md += `### ${p.name}\n${p.note}\n\n`;
    for (const [ref, text] of ex) md += `- **${ref}** — ${text}\n`;
    md += `\n`;
  }
} else {
  md += `> No \`incontext_patterns\` defined in the profile — pack is core-vocabulary only. Add pattern banks to the profile to anchor grammar (see profiles/_template.json).\n`;
}

writeFileSync(outPath, md);
console.log(`✓ wrote ${outPath} (${CORE.length} core words, ${PATTERNS.length} pattern banks, ${(md.length / 1024).toFixed(1)} KB)`);
