#!/usr/bin/env bun
/**
 * generate-system-instruction.ts — build the paste-ready drafting system prompt
 * for the active language FROM the profile + reference pack, in the team's LWC.
 *
 * This removes the last hardcoded-English / hardcoded-language bottleneck: instead
 * of hand-editing a 60-line instruction block per language, the block is generated
 * from data the team already maintains (profile + references/).
 *
 * It loads, in order, whatever reference files exist and stitches them into a
 * single instruction. Missing files are skipped (with a note), so it works from
 * day one and gets richer as the reference pack fills in.
 *
 * Usage:
 *   bun tools/generate-system-instruction.ts [--profile profiles/<iso>.json] [--genre narrative] [> drafting-instruction.md]
 */
import { existsSync, readFileSync } from "fs";
import { join } from "path";
import { loadProfile } from "./lib/profile.ts";

const profile = loadProfile();
const genreArg = (() => { const i = process.argv.indexOf("--genre"); return i >= 0 ? process.argv[i + 1] : null; })();

const packDir = profile.paths.reference_pack ?? join((new URL("../", import.meta.url)).pathname, "references");
const iso = profile.iso639_3;

// Try a few naming conventions for each reference component.
function findRef(stem: string): string | null {
  const candidates = [
    join(packDir, `${iso}-${stem}.md`),
    join(packDir, `${stem}.md`),
  ];
  for (const c of candidates) if (existsSync(c)) return c;
  return null;
}
function section(stem: string): string | null {
  const p = findRef(stem);
  return p ? readFileSync(p, "utf8").trim() : null;
}

const lwc = profile.lwc[0] || "the language of wider communication";
const keyTerms = Object.entries(profile.key_terms_anchor);

let out = "";
out += `# Drafting system instruction — ${profile.language} (${iso})\n\n`;
out += `> Auto-generated by tools/generate-system-instruction.ts from the profile + reference pack. Paste this as the system / first message when drafting. Re-generate after editing the profile or references.\n\n`;

out += `You are drafting Scripture in **${profile.language}** (ISO ${iso}), ${profile.script}, matching the register of the ${profile.language} corpus loaded in context. You are NOT writing in ${lwc} or any other wider-communication language, and you are not writing a neighboring or prestige variety. Your single biggest risk is leaking those varieties in.\n\n`;

if (profile.divine_name) out += `**Divine name:** render as **${profile.divine_name}**.\n\n`;

if (keyTerms.length) {
  out += `**Key terms (use these established renderings):**\n`;
  for (const [k, v] of keyTerms) out += `- ${k} → ${v}\n`;
  out += `\n`;
}

if (Object.keys(profile.borrowings).length) {
  out += `**Do NOT use these borrowings — use the local form:**\n`;
  for (const [k, v] of Object.entries(profile.borrowings)) out += `- ${k} → ${v}\n`;
  out += `\n`;
}

// Hard rules distilled from the linter (so the model avoids them up front).
if (profile.linter_rules.length) {
  out += `**Hard rules (the verifier will flag these):**\n`;
  for (const r of profile.linter_rules) out += `- [${r.severity}] ${r.message}\n`;
  out += `\n`;
}

const COMPONENTS: [string, string][] = [
  ["common-errors", "Common errors — read first, weight heavily (the negative prompt)"],
  ["incontext-pack", "In-context pack — real attested examples (learn from these, not from rules)"],
  ["narrative-exemplars", "Narrative exemplars — real attested passages to imitate"],
  ["draft-annotation", "How to mark uncertainty ⟨?⟩, options {A ⟂ B}, and warrants"],
  ["translation-issues", "Issue taxonomy — when to offer options instead of committing"],
  ["proper-names", "Proper names — fixed list + transliteration rules"],
  ["key-terms", "Key terms reference"],
  ["orthography", "Orthography / romanization rules"],
  ["grammar", "Grammar reference"],
  ["style-guide", "Style guide — vocabulary + register"],
];

out += `---\n\n## Reference pack\n\n`;
const missing: string[] = [];
for (const [stem, title] of COMPONENTS) {
  const body = section(stem);
  if (!body) { missing.push(stem); continue; }
  out += `### ${title}\n\n${body}\n\n`;
}

out += `---\n\n## Procedure\n\n`;
out += `1. Draft the passage verse by verse in ${profile.language}.\n`;
out += `2. Where you are unsure of a word or rendering, mark it ⟨?⟩ and, if you have alternatives, give them as {option A ⟂ option B} with a one-line warrant.\n`;
out += `3. Prefer vocabulary and constructions attested in the in-context pack. If a word you want is not attested, it is probably a borrowing — find the local form or mark it ⟨?⟩.\n`;
out += `4. Output verse-keyed JSON: {"verses": {"<Book>:<ch>:<v>": "draft text", ...}} so the verifier (tools/check-draft.ts, tools/score-draft.ts) can read it.\n`;
if (genreArg) out += `\nGenre focus for this run: **${genreArg}** — lean on the matching narrative/poetic exemplars above.\n`;

if (missing.length) out += `\n> Note: reference components not yet built (skipped): ${missing.join(", ")}. Add them to ${packDir} to enrich this instruction.\n`;

console.log(out);
